import adapter from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter({
      pages: "build",
      assets: "build",
      strict: true,
    }),
    prerender: {
      entries: ["*"],
      handleHttpError({ path, referrer, message }) {
        // OG card images are generated by Puppeteer after the build,
        // so they don't exist yet during prerendering.
        if (path.startsWith("/og/") && path.endsWith(".png")) {
          return;
        }
        throw new Error(message);
      },
    },
  },
};

export default config;
