// Regenerates the wireframe globe's line geometry from Natural Earth's 110m
// country polygons, shipped by the `world-atlas` package. Ported from the
// working prototype at `.cc-scratch/design/build/extract.mjs` (#178) -
// typed, and split into named, individually testable pure functions.
//
// Run with `npm run generate-geo` whenever world-atlas is upgraded or the
// simplification tolerances change. The committed output at
// static/landing/globe-lines.json is what globe.ts fetches at runtime: this
// project generates its PDFs and OG images at Docker build time and does
// not commit them, but the globe needs to render under `npm run dev` with
// no separate manual step, and nothing here depends on the site being
// built or served first (unlike the PDF/OG scripts, which need a running
// preview server). So the tradeoff differs and the generated payload is
// committed instead, regenerated by this script on demand like
// generate-apple-touch-icon.ts's output is regenerated on demand, just
// checked in rather than produced fresh on every build.
//
// There is no pre-rendered still image for the reduced-motion/no-WebGL/
// no-JS fallback cases: Hero.svelte already carries a `.hero-backdrop`
// radial-gradient layer for the landing redesign (#177), and that is the
// static backdrop those cases fall back to - see Hero.svelte.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { feature } from "topojson-client";
import type { Topology } from "topojson-specification";
import type { MultiPolygon, Polygon } from "geojson";

type Ring = [number, number][];

export interface GlobeLines {
  world: string[];
  canada: string[];
}

const WORLD_TOLERANCE_DEG = 0.55;
const CANADA_TOLERANCE_DEG = 0.35;
const MIN_RING_POINTS = 3;
const COORDINATE_PRECISION = 1; // decimal places (~0.1 degree, ~11km)
const ANTIMERIDIAN_SPAN_DEG = 180;

const TOPOLOGY_PATH = resolve("node_modules", "world-atlas", "countries-110m.json");
const OUTPUT_PATH = resolve("static", "landing", "globe-lines.json");

// Perpendicular distance from `point` to the line through `a`-`b`, in the
// flat lon/lat plane. Good enough here: the distortion it ignores is far
// smaller than the 0.1 degree rounding applied after simplification.
function perpendicular_distance(point: [number, number], a: [number, number], b: [number, number]): number {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  if (dx === 0 && dy === 0) {
    return Math.hypot(point[0] - a[0], point[1] - a[1]);
  }
  const t = ((point[0] - a[0]) * dx + (point[1] - a[1]) * dy) / (dx * dx + dy * dy);
  const closest_x = a[0] + t * dx;
  const closest_y = a[1] + t * dy;
  return Math.hypot(point[0] - closest_x, point[1] - closest_y);
}

// Douglas-Peucker simplification of a ring's points, in the flat lon/lat
// plane, to within `tolerance_deg`.
export function simplify_ring(points: Ring, tolerance_deg: number): Ring {
  if (points.length < 3) {
    return points;
  }
  let max_distance = 0;
  let split_index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const distance = perpendicular_distance(points[i], points[0], points[points.length - 1]);
    if (distance > max_distance) {
      max_distance = distance;
      split_index = i;
    }
  }
  if (max_distance <= tolerance_deg) {
    return [points[0], points[points.length - 1]];
  }
  return [
    ...simplify_ring(points.slice(0, split_index + 1), tolerance_deg).slice(0, -1),
    ...simplify_ring(points.slice(split_index), tolerance_deg),
  ];
}

// A ring that crosses the antimeridian would otherwise draw a straight line
// clear across the map at +/-180 degrees longitude. Split wherever a
// consecutive pair spans more than 180 degrees of longitude so nothing does.
export function split_at_antimeridian(ring: Ring): Ring[] {
  const pieces: Ring[] = [];
  let current: Ring = [ring[0]];
  for (let i = 1; i < ring.length; i++) {
    if (Math.abs(ring[i][0] - ring[i - 1][0]) > ANTIMERIDIAN_SPAN_DEG) {
      pieces.push(current);
      current = [ring[i]];
    } else {
      current.push(ring[i]);
    }
  }
  pieces.push(current);
  return pieces.filter((piece) => piece.length > 1);
}

function rings_of(geometry: Polygon | MultiPolygon): Ring[] {
  if (geometry.type === "Polygon") {
    return geometry.coordinates as Ring[];
  }
  return (geometry.coordinates as Ring[][]).flat();
}

// Simplifies, splits at the seam, rounds to one decimal place, and encodes
// each ring as a single "lon,lat lon,lat ..." string.
function encode_rings(rings: Ring[], tolerance_deg: number): string[] {
  const encoded: string[] = [];
  for (const ring of rings) {
    for (const piece of split_at_antimeridian(ring)) {
      const simplified = simplify_ring(piece, tolerance_deg);
      if (simplified.length < MIN_RING_POINTS) {
        continue;
      }
      encoded.push(
        simplified
          .map(([lon, lat]) => `${lon.toFixed(COORDINATE_PRECISION)},${lat.toFixed(COORDINATE_PRECISION)}`)
          .join(" "),
      );
    }
  }
  return encoded;
}

// Throws if any encoded ring still contains a segment spanning the
// antimeridian - a self-check against the invariant `split_at_antimeridian`
// is supposed to guarantee, run against the actual generated payload before
// it's written. (The other geometry invariant, that every rendered vertex
// lands on the unit sphere, is a property of how globe.ts projects these
// lon/lat pairs, not of this script's output, so it's covered by
// globe.test.ts instead.)
export function assert_no_antimeridian_span(rings: string[], label: string): void {
  for (const ring of rings) {
    const points = ring.split(" ").map((pair) => pair.split(",").map(Number) as [number, number]);
    for (let i = 1; i < points.length; i++) {
      if (Math.abs(points[i][0] - points[i - 1][0]) > ANTIMERIDIAN_SPAN_DEG) {
        throw new Error(`${label} ring segment spans the antimeridian: ${points[i - 1]} -> ${points[i]}`);
      }
    }
  }
}

export function build_globe_lines(topology: Topology): GlobeLines {
  const countries = feature(topology, topology.objects.countries as never);
  const world_rings: string[] = [];
  let canada_rings: string[] = [];

  for (const country of countries.features) {
    const rings = rings_of(country.geometry as Polygon | MultiPolygon);
    if (country.properties?.name === "Canada") {
      canada_rings = encode_rings(rings, CANADA_TOLERANCE_DEG);
    } else {
      world_rings.push(...encode_rings(rings, WORLD_TOLERANCE_DEG));
    }
  }

  assert_no_antimeridian_span(world_rings, "world");
  assert_no_antimeridian_span(canada_rings, "canada");

  return { world: world_rings, canada: canada_rings };
}

function point_count(rings: string[]): number {
  return rings.reduce((total, ring) => total + ring.split(" ").length, 0);
}

function main(): void {
  const topology = JSON.parse(readFileSync(TOPOLOGY_PATH, "utf-8")) as Topology;
  const lines = build_globe_lines(topology);
  const json = JSON.stringify(lines);

  writeFileSync(OUTPUT_PATH, json);

  console.log(
    `world: ${lines.world.length} rings / ${point_count(lines.world)} points, ` +
      `canada: ${lines.canada.length} rings / ${point_count(lines.canada)} points, ` +
      `${(json.length / 1024).toFixed(1)} KB -> ${OUTPUT_PATH}`,
  );
}

main();
